development:
    secret_key_base: c66ee08f1ca987f51b9c14be00a3951d9bdce9066ec7d6e95c44fdf281549c05f1b9ab60edc5b75365c1d6c93469419574d23b89dbb8184c5b0e5b5890fb5a04
    cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
    cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
    cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
test:
    cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
    cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
    cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
production:
    secret_key_base: c66ee08f1ca987f51b9c14be00a3951d9bdce9066ec7d6e95c44fdf281549c05f1b9ab60edc5b75365c1d6c93469419574d23b89dbb8184c5b0e5b5890fb5a04
    cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
    cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
    cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
